# Generated by Django 3.2.8 on 2021-10-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacttable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contacts',
        ),
    ]
