# Generated by Django 3.2.8 on 2021-10-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacttable', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
