# Generated by Django 3.2.8 on 2021-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacttable', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Photo',
            field=models.FileField(upload_to='photos'),
        ),
    ]
